# Autogenerated wrapper script for Conspire_jll for aarch64-apple-darwin
export libconspire_wrapper

JLLWrappers.@generate_wrapper_header("Conspire")
JLLWrappers.@declare_library_product(libconspire_wrapper, "@rpath/libconspire_wrapper.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libconspire_wrapper,
        "lib/conspire_wrapper.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
